// Copyright (c) Microsoft. All rights reserved.

using System;
using System.Buffers;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.Text.Json;
using Azure.AI.AgentServer.Responses;
using Azure.AI.AgentServer.Responses.Models;
using Microsoft.Extensions.AI;
using ChatMessage = Microsoft.Extensions.AI.ChatMessage;
using ComputerCallAction = OpenAI.Responses.ComputerCallAction;
using OpenAIComputerCallOutputResponseItem = OpenAI.Responses.ComputerCallOutputResponseItem;
using OpenAIComputerCallResponseItem = OpenAI.Responses.ComputerCallResponseItem;
using OpenAIContext = OpenAI.OpenAIContext;
using OpenAIResponseItem = OpenAI.Responses.ResponseItem;

namespace Microsoft.Agents.AI.Foundry.Hosting;

/// <summary>
/// Converts computer tool items (<c>computer_call</c> and <c>computer_call_output</c>) between the AgentServer
/// Responses models and the OpenAI .NET models that the MEAI OpenAI Responses client sends to the model.
/// </summary>
/// <remarks>
/// <para>
/// Both SDKs generate their models from the same OpenAI wire schema, but neither can build the other's item, and
/// OpenAI .NET (2.13.0 and 2.14.0) has no typed GA <c>actions</c> batch. The item is therefore converted through its
/// JSON: fields one SDK does not type (such as <c>actions</c> or the screenshot <c>detail</c>) travel as additional
/// data. Replace this with typed conversions once OpenAI .NET models the GA computer items.
/// </para>
/// <para>
/// The OpenAI item is carried as the <see cref="AIContent.RawRepresentation"/> of a <see cref="ToolCallContent"/> or
/// <see cref="ToolResultContent"/>. The MEAI OpenAI Responses client sends any content whose raw representation is a
/// <see cref="OpenAIResponseItem"/> to the model unchanged, which is what keeps the batch intact on replay. Computer
/// calls sent back to the model are a <see cref="ResentComputerCallResponseItem"/>, which writes the GA shape.
/// </para>
/// </remarks>
internal static class ComputerToolItemConverter
{
    /// <summary>Converts a <c>computer_call</c> sent as request input into an assistant message.</summary>
    public static ChatMessage ToChatMessage(ItemComputerToolCall item) =>
        ToToolCallMessage(Write(WithSafetyCheckList(item)), item.CallId);

    /// <summary>Converts a <c>computer_call</c> loaded from AgentServer history into an assistant message.</summary>
    public static ChatMessage ToChatMessage(OutputItemComputerToolCall item) =>
        ToToolCallMessage(Write(WithSafetyCheckList(item)), item.CallId);

    /// <summary>Converts a <c>computer_call_output</c> sent as request input into a tool message.</summary>
    public static ChatMessage ToChatMessage(ComputerCallOutputItemParam item) =>
        ToToolResultMessage(Write(item), item.CallId);

    /// <summary>Converts a <c>computer_call_output</c> loaded from AgentServer history into a tool message.</summary>
    public static ChatMessage ToChatMessage(OutputItemComputerToolCallOutput item) =>
        ToToolResultMessage(Write(item), item.CallId);

    /// <summary>Converts a model <c>computer_call</c> into the output item emitted to the caller.</summary>
    /// <param name="item">The computer call returned by the model.</param>
    /// <param name="itemId">The id generated by the AgentServer output item builder.</param>
    public static OutputItemComputerToolCall ToOutputItem(OpenAIComputerCallResponseItem item, string itemId) =>
        ReadAgentServerItem<OutputItemComputerToolCall>(WriteOpenAI(item), itemId, "computer_call", item.CallId);

    /// <summary>Converts a <c>computer_call_output</c> produced by the agent into the output item emitted to the caller.</summary>
    /// <param name="item">The computer call output produced by the agent.</param>
    /// <param name="itemId">The id generated by the AgentServer output item builder.</param>
    public static OutputItemComputerToolCallOutput ToOutputItem(OpenAIComputerCallOutputResponseItem item, string itemId) =>
        ReadAgentServerItem<OutputItemComputerToolCallOutput>(WriteOpenAI(item), itemId, "computer_call_output", item.CallId);

    private static BinaryData WriteOpenAI<T>(T item)
        where T : IPersistableModel<T> =>
        ModelReaderWriter.Write(item, ModelReaderWriterOptions.Json, OpenAIContext.Default);

    private static T ReadAgentServerItem<T>(BinaryData openAIJson, string itemId, string itemType, string callId)
        where T : OutputItem
    {
        // The builder id replaces the model's item id: AgentServer requires its own {prefix}_{50 chars} id format and
        // does not stamp one on EmitAdded. Leaving out a null "action" keeps the emitted item in the GA shape (actions
        // only).
        BinaryData agentServerJson = RewriteTopLevelProperties(openAIJson, IsNullAction, replacementId: itemId);

        return ModelReaderWriter.Read<OutputItem>(agentServerJson, ModelReaderWriterOptions.Json, AzureAIAgentServerResponsesContext.Default) as T
            ?? throw new InvalidOperationException(
                $"The {itemType} item for call '{callId}' could not be converted to the AgentServer {typeof(T).Name} representation.");
    }

    private static BinaryData Write<T>(T item)
        where T : IPersistableModel<T> =>
        ModelReaderWriter.Write(item, ModelReaderWriterOptions.Json, AzureAIAgentServerResponsesContext.Default);

    // The GA computer_call has no "pending_safety_checks". AgentServer (1.0.0-beta.8) then leaves PendingSafetyChecks
    // null and its serializer throws NullReferenceException, so such an item is rebuilt with an empty list first. The
    // rebuilt item keeps every typed field; the list has no public setter, which is why a copy is needed.
    private static ItemComputerToolCall WithSafetyCheckList(ItemComputerToolCall item)
    {
        if (item.PendingSafetyChecks is not null)
        {
            return item;
        }

        var copy = new ItemComputerToolCall(item.Id, item.CallId, [], item.Status) { Action = item.Action };
        CopyActions(item.Actions, copy.Actions);
        return copy;
    }

    private static OutputItemComputerToolCall WithSafetyCheckList(OutputItemComputerToolCall item)
    {
        if (item.PendingSafetyChecks is not null)
        {
            return item;
        }

        // The AgentServer envelope (response id, agent reference) is not copied: it is dropped before replay anyway.
        var copy = new OutputItemComputerToolCall(item.Id, item.CallId, [], item.Status) { Action = item.Action };
        CopyActions(item.Actions, copy.Actions);
        return copy;
    }

    private static void CopyActions(IList<ComputerAction>? source, IList<ComputerAction> target)
    {
        if (source is null)
        {
            return;
        }

        foreach (ComputerAction action in source)
        {
            target.Add(action);
        }
    }

    private static ChatMessage ToToolCallMessage(BinaryData agentServerJson, string callId)
    {
        // OpenAI .NET (2.13.0 and 2.14.0) models only the preview item: ComputerCallResponseItem always writes "action",
        // so a GA call sent back as that type would carry "action": null next to "actions", which the Responses API
        // rejects. Its Patch API cannot remove "action" (NullReferenceException), so the item is wrapped in a subclass
        // that writes this JSON as is. The JSON also drops a null "action" in case a caller sent one.
        BinaryData openAIJson = RewriteTopLevelProperties(
            agentServerJson,
            static property => IsAgentServerEnvelopeProperty(property) || IsNullAction(property));
        var item = ReadOpenAIItem<OpenAIComputerCallResponseItem>(openAIJson, "computer_call", callId);
        return new ChatMessage(
            ChatRole.Assistant,
            [new ToolCallContent(callId) { RawRepresentation = new ResentComputerCallResponseItem(item, openAIJson) }]);
    }

    private static ChatMessage ToToolResultMessage(BinaryData agentServerJson, string callId)
    {
        BinaryData openAIJson = RewriteTopLevelProperties(agentServerJson, IsAgentServerEnvelopeProperty);
        var item = ReadOpenAIItem<OpenAIComputerCallOutputResponseItem>(openAIJson, "computer_call_output", callId);
        return new ChatMessage(ChatRole.Tool, [new ToolResultContent(callId) { RawRepresentation = item }]);
    }

    private static T ReadOpenAIItem<T>(BinaryData openAIJson, string itemType, string callId)
        where T : OpenAIResponseItem =>
        ModelReaderWriter.Read<OpenAIResponseItem>(openAIJson, ModelReaderWriterOptions.Json, OpenAIContext.Default) as T
            ?? throw new InvalidOperationException(
                $"The {itemType} item for call '{callId}' could not be converted to the OpenAI {typeof(T).Name} representation.");

    /// <summary>
    /// AgentServer adds these fields to stored output items. They are not part of the model's item schema, and the
    /// model API rejects unknown input parameters, so they must not be replayed.
    /// </summary>
    private static bool IsAgentServerEnvelopeProperty(JsonProperty property) =>
        property.NameEquals("response_id"u8) ||
        property.NameEquals("agent_reference"u8) ||
        property.NameEquals("created_by"u8);

    /// <summary>
    /// A null <c>"action"</c> is how OpenAI .NET writes a GA call. A populated preview <c>"action"</c> is kept.
    /// </summary>
    private static bool IsNullAction(JsonProperty property) =>
        property.NameEquals("action"u8) && property.Value.ValueKind == JsonValueKind.Null;

    /// <summary>
    /// Copies a JSON object, leaving out the top-level properties selected by <paramref name="skip"/> and, when
    /// <paramref name="replacementId"/> is set, replacing its <c>id</c>.
    /// </summary>
    private static BinaryData RewriteTopLevelProperties(BinaryData json, Func<JsonProperty, bool> skip, string? replacementId = null)
    {
        using JsonDocument document = JsonDocument.Parse(json);
        var buffer = new ArrayBufferWriter<byte>();
        using (var writer = new Utf8JsonWriter(buffer))
        {
            writer.WriteStartObject();
            if (replacementId is not null)
            {
                writer.WriteString("id"u8, replacementId);
            }

            foreach (JsonProperty property in document.RootElement.EnumerateObject())
            {
                if (skip(property) || (replacementId is not null && property.NameEquals("id"u8)))
                {
                    continue;
                }

                property.WriteTo(writer);
            }

            writer.WriteEndObject();
        }

        return new BinaryData(buffer.WrittenMemory.ToArray());
    }

    /// <summary>
    /// A <see cref="OpenAIComputerCallResponseItem"/> that is sent back to the model with the JSON it was read from.
    /// </summary>
    /// <remarks>
    /// Callers still see the typed OpenAI item (<c>CallId</c>, <c>Id</c>, <c>Status</c>, <c>Action</c>), but the item is
    /// written as the computer call it was read from, so a GA call keeps its <c>actions</c> batch without the
    /// <c>"action": null</c> the base type would add. Changes to the typed properties are not written. Remove this
    /// once OpenAI .NET models the GA computer call.
    /// </remarks>
    private sealed class ResentComputerCallResponseItem : OpenAIComputerCallResponseItem
    {
        private readonly BinaryData _json;

        public ResentComputerCallResponseItem(OpenAIComputerCallResponseItem item, BinaryData json)
            // The only public constructor requires an action, which a GA call does not have. A placeholder satisfies
            // it and is replaced right away, so Action reads null for a GA call as it does on the parsed item.
            : base(item.CallId, item.Action ?? ComputerCallAction.CreateScreenshotAction(), item.PendingSafetyChecks)
        {
            this._json = json;
            this.Action = item.Action;
            this.Status = item.Status;
            this.Id = item.Id;
        }

        protected override void JsonModelWriteCore(Utf8JsonWriter writer, ModelReaderWriterOptions options)
        {
            using JsonDocument document = JsonDocument.Parse(this._json);
            foreach (JsonProperty property in document.RootElement.EnumerateObject())
            {
                property.WriteTo(writer);
            }
        }
    }
}
