// Copyright (c) Microsoft. All rights reserved.

// This sample shows how to use Bing Grounding Tool with AI Agents.

using Azure.AI.Projects;
using Azure.AI.Projects.OpenAI;
using Azure.Identity;
using Microsoft.Agents.AI;
using Microsoft.Extensions.AI;
using OpenAI.Responses;

string endpoint = Environment.GetEnvironmentVariable("AZURE_FOUNDRY_PROJECT_ENDPOINT") ?? throw new InvalidOperationException("AZURE_FOUNDRY_PROJECT_ENDPOINT is not set.");
string deploymentName = Environment.GetEnvironmentVariable("AZURE_FOUNDRY_PROJECT_DEPLOYMENT_NAME") ?? "gpt-4o-mini";
string bingConnectionId = Environment.GetEnvironmentVariable("BING_PROJECT_CONNECTION_ID") ?? throw new InvalidOperationException("BING_PROJECT_CONNECTION_ID is not set.");

const string AgentInstructions =
    """
    You are a helpful assistant that can search the web for current information.
    Use the Bing search tool to find up-to-date information and provide accurate, well-sourced answers.
    Always cite your sources when possible.
    """;

const string AgentNameMEAI = "BingGroundingAgent-MEAI";
const string AgentNameNative = "BingGroundingAgent-NATIVE";

// Get a client to create/retrieve/delete server side agents with Azure Foundry Agents.
AIProjectClient aiProjectClient = new(new Uri(endpoint), new AzureCliCredential());

// Option 1 - Using HostedWebSearchTool + AgentOptions (MEAI + AgentFramework)
// Create the server side agent version
AIAgent agentOption1 = await aiProjectClient.CreateAIAgentAsync(
    model: deploymentName,
    name: AgentNameMEAI,
    instructions: AgentInstructions,
    tools: [new HostedWebSearchTool(new Dictionary<string, object?> { ["connectionId"] = bingConnectionId })]);

// Option 2 - Using PromptAgentDefinition SDK native type with AgentTool.CreateBingGroundingTool
// Create the server side agent version
AIAgent agentOption2 = await aiProjectClient.CreateAIAgentAsync(
    name: AgentNameNative,
    creationOptions: new AgentVersionCreationOptions(
        new PromptAgentDefinition(model: deploymentName)
        {
            Instructions = AgentInstructions,
            Tools = {
                (ResponseTool)AgentTool.CreateBingGroundingTool(
                    new BingGroundingSearchToolOptions([
                        new BingGroundingSearchConfiguration(bingConnectionId)
                    ])
                )
            }
        })
);

// Either invoke option1 or option2 agent, should have same result
// Option 1
AgentResponse response = await agentOption1.RunAsync("What are the latest developments in AI this week?");

// Option 2
// AgentResponse response = await agentOption2.RunAsync("What are the latest developments in AI this week?");

// Display the response
foreach (ChatMessage message in response.Messages)
{
    foreach (AIContent content in message.Contents)
    {
        if (content is TextContent textContent)
        {
            Console.WriteLine($"Response: {textContent.Text}");
        }
    }
}

// Getting any URL citation annotations generated by the Bing Grounding tool
foreach (AIAnnotation annotation in response.Messages.SelectMany(m => m.Contents).SelectMany(c => c.Annotations ?? []))
{
    if (annotation.RawRepresentation is UriCitationMessageAnnotation urlCitation)
    {
        Console.WriteLine($"Citation: {urlCitation.Title} - {urlCitation.Uri}");
    }
}

// Cleanup by agent name removes the agent version created.
await aiProjectClient.Agents.DeleteAgentAsync(agentOption1.Name);
await aiProjectClient.Agents.DeleteAgentAsync(agentOption2.Name);