// Copyright (c) Microsoft. All rights reserved.

// This sample shows how to use File Search Tool with AI Agents.

using Azure.AI.Projects;
using Azure.AI.Projects.OpenAI;
using Azure.Identity;
using Microsoft.Agents.AI;
using Microsoft.Extensions.AI;
using OpenAI.Assistants;
using OpenAI.Files;
using OpenAI.Responses;

string endpoint = Environment.GetEnvironmentVariable("AZURE_FOUNDRY_PROJECT_ENDPOINT") ?? throw new InvalidOperationException("AZURE_FOUNDRY_PROJECT_ENDPOINT is not set.");
string deploymentName = Environment.GetEnvironmentVariable("AZURE_FOUNDRY_PROJECT_DEPLOYMENT_NAME") ?? "gpt-4o-mini";

const string AgentInstructions = "You are a helpful assistant that can search through uploaded files to answer questions.";
const string AgentNameMEAI = "FileSearchAgent-MEAI";
const string AgentNameNative = "FileSearchAgent-NATIVE";

// Get a client to create/retrieve/delete server side agents with Azure Foundry Agents.
AIProjectClient aiProjectClient = new(new Uri(endpoint), new AzureCliCredential());
var projectOpenAIClient = aiProjectClient.GetProjectOpenAIClient();
var filesClient = projectOpenAIClient.GetProjectFilesClient();
var vectorStoresClient = projectOpenAIClient.GetProjectVectorStoresClient();

// 1. Create a temp file with test content and upload it.
string searchFilePath = Path.GetTempFileName() + "_lookup.txt";
File.WriteAllText(
    path: searchFilePath,
    contents: """
        Employee Directory:
        - Alice Johnson, 28 years old, Software Engineer, Engineering Department
        - Bob Smith, 35 years old, Sales Manager, Sales Department
        - Carol Williams, 42 years old, HR Director, Human Resources Department
        - David Brown, 31 years old, Customer Support Lead, Support Department
        """
);

Console.WriteLine($"Uploading file: {searchFilePath}");
OpenAIFile uploadedFile = filesClient.UploadFile(
    filePath: searchFilePath,
    purpose: FileUploadPurpose.Assistants
);
Console.WriteLine($"Uploaded file, file ID: {uploadedFile.Id}");

// 2. Create a vector store with the uploaded file.
var vectorStoreResult = await vectorStoresClient.CreateVectorStoreAsync(
    options: new() { FileIds = { uploadedFile.Id }, Name = "EmployeeDirectory_VectorStore" }
);
string vectorStoreId = vectorStoreResult.Value.Id;
Console.WriteLine($"Created vector store, vector store ID: {vectorStoreId}");

// Option 1 - Using HostedFileSearchTool + AgentOptions (MEAI + AgentFramework)
// Create the server side agent version with file search capabilities.
AIAgent agentOption1 = await aiProjectClient.CreateAIAgentAsync(
    model: deploymentName,
    name: AgentNameMEAI,
    instructions: AgentInstructions,
    tools: [new HostedFileSearchTool() { Inputs = [new HostedVectorStoreContent(vectorStoreId)] }]);

// Option 2 - Using PromptAgentDefinition SDK native type
// Create the server side agent version.
AIAgent agentOption2 = await aiProjectClient.CreateAIAgentAsync(
    name: AgentNameNative,
    creationOptions: new AgentVersionCreationOptions(
        new PromptAgentDefinition(model: deploymentName)
        {
            Instructions = AgentInstructions,
            Tools = {
                ResponseTool.CreateFileSearchTool(vectorStoreIds: [vectorStoreId])
            }
        })
);

// Either invoke option1 or option2 agent, should have same result
// Option 1
Console.WriteLine("\n--- Running File Search Agent (Option 1 - MEAI) ---");
AgentResponse response1 = await agentOption1.RunAsync("Who is the youngest employee?");
Console.WriteLine($"Response: {response1}");

// Option 2
Console.WriteLine("\n--- Running File Search Agent (Option 2 - Native) ---");
AgentResponse response2 = await agentOption2.RunAsync("Who works in the Sales Department?");
Console.WriteLine($"Response: {response2}");

// Getting any file citation annotations generated by the tool
foreach (AIAnnotation annotation in response1.Messages.SelectMany(m => m.Contents).SelectMany(c => c.Annotations ?? []))
{
    if (annotation.RawRepresentation is TextAnnotationUpdate citationAnnotation)
    {
        Console.WriteLine($$"""
            File Citation:
              File Id: {{citationAnnotation.OutputFileId}}
              Text to Replace: {{citationAnnotation.TextToReplace}}
            """);
    }
}

// Cleanup.
Console.WriteLine("\n--- Cleanup ---");
await aiProjectClient.Agents.DeleteAgentAsync(agentOption1.Name);
await aiProjectClient.Agents.DeleteAgentAsync(agentOption2.Name);
await vectorStoresClient.DeleteVectorStoreAsync(vectorStoreId);
await filesClient.DeleteFileAsync(uploadedFile.Id);
File.Delete(searchFilePath);
Console.WriteLine("Cleanup completed successfully.");
